install:
  - cp tests/options.docker_compose_example.yml tests/options.yml
  - docker-compose build
script:
  - "echo 'TODO: run user creation script'"
  - docker-compose run python_libstorj bash -c "./build.sh && python -m unittest discover"
